import IMGThree from '../../../img/piratesofthecaribbean3.jpg'
import IMGTwo from '../../../img/piratesofthecaribbean2.jpg'
import IMG from '../../../img/piratesofthecaribbean1.jpg'
import SangChi from '../../../img/SangChi.jpg'
import SpyderManNWH from '../../../img/Spidermannowayhome.jpg'